set_property PACKAGE_PIN F2 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN F1 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN G2 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN G1 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_sws[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_sws[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_sws[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_sws[0]}]
set_property PACKAGE_PIN T2 [get_ports {s_sws[3]}]
set_property PACKAGE_PIN U1 [get_ports {s_sws[2]}]
set_property PACKAGE_PIN U2 [get_ports {s_sws[1]}]
set_property PACKAGE_PIN V2 [get_ports {s_sws[0]}]

